### ISSUE TITLE
Earth seasons changes

### ISSUE THREAD

**Issue by Deuchnord** [Kosmorro/lib#23]
**Event type**: earth seasons changes
**Involved objects (check the boxes)**:
- [ ] Sun
- [x] Earth
- [ ] Earth's moon
- [ ] Planets

**Definition of the event:**

> A season is a division of the year based on changes in […] and the number of daylight hours in a given region. On Earth, seasons are the result of Earth's orbit around the Sun and Earth's axial tilt relative to the ecliptic plane.
> — [Wikipedia](https://en.wikipedia.org/wiki/Season)

The four astronomical seasons on Earth are:
- Winter solstice
- Spring equinox
- Summer solstice
- Autumn equinox

> A solstice is an event that occurs when the Sun appears to reach its most northerly or southerly excursion relative to the celestial equator on the celestial sphere.
> — [Wikipedia](https://en.wikipedia.org/wiki/Solstice)

> An equinox is the instant of time when the plane of Earth's equator passes through the geometric center of the Sun's disk
> — [Wikipedia](https://en.wikipedia.org/wiki/Equinox)

**Other useful information** (implementation proposal, etc):
Skyfield library has [built-in capabilities](https://rhodesmill.org/skyfield/almanac.html#the-seasons) to determine when a season change occurs.
This should be integrated to the `get_events()` function.

**Comment by dragontunglam** [comment]
Hello, I came across your issue and gave it a try. Please review my pull request. Thank you.
