### ISSUE TITLE
Use skyfield-data to get the needed files

### ISSUE THREAD

**Issue by thierry-FreeBSD** [Kosmorro/lib#4]
As noted in readme, "the first time it runs, Kosmorro will download some important files needed to make the computations".
These files (e.g. de421.bsp) could be available after installation of https://github.com/brunobord/skyfield-data (also available from https://pypi.org/project/skyfield-data/ ).

**Comment by thierry-FreeBSD** [comment]
> This issue has not been active since a lot of time. If you think it is still valid, feel free to reply with a simple comment. Without any update, I will close it in 7 days.

Keep alive.

**Comment by Deuchnord** [comment]
Closing this issue, feature implemented in #22 for version 1.0.0 :tada:
