### ISSUE TITLE
Add a function to search for events

### ISSUE THREAD

**Issue by Deuchnord** [Kosmorro/lib#43]
Add a way to search conveniently for events types between two dates:

```python
# kosmorrolib/events.py
def search_events(event_types: [EventType], until: date, from: date = date.today()) -> [Event]
```

When used, this function searches for the given `EventType` values between the `from` and the `until` dates (both inclusive), and returns a list of `Event` objects that correspond to the request.

In some ways, this function's behavior is very similar to the `get_events()`, but it filters out the unwanted `EventType`s.

**Comment by nicfb** [comment]
Hello! If you haven't already started work on this, I would love to try.

**Comment by Deuchnord** [comment]
I didn't, you can take it :)
